**ChatGPT is forbidden**

**Data generation**

Create and visualize arrays containing only real numbers, then integers, then strings, then a mix of integers and strings

In [2]:
import numpy as np
x=np.array([1,2,3])
y=np.array([4,5,6])
print(np.array(["a","b","c"]))
print(np.array([1,2,3]))
print(np.array([4,5,6]))
print(np.array([.1,.2,.3]))
mixed_array = np.array(["a", 2, 3])
print(mixed_array)



['a' 'b' 'c']
[1 2 3]
[4 5 6]
[0.1 0.2 0.3]
['a' '2' '3']


Add two arrays made of integers, element by element (the two arrays must be the same size)

In [12]:
x+y

array([5, 7, 9])

Create a 3*3 array including only zeros on the first line, then 1s on the second line, then the number 5 on the third line

In [15]:
z=np.array([[0,0,0],
            [1,1,1],
            [3,3,3]])
z

array([[0, 0, 0],
       [1, 1, 1],
       [3, 3, 3]])

Extract the shape attribute from this array

In [16]:
print(z.shape)

(3, 3)


Create an array of 3 by 3 by 3 including only real numbers chosen from a normal distribution

In [4]:
print(np.random.normal(size=(3, 3, 3)))

[[[ 1.26456831 -0.48055146 -1.16248077]
  [-0.01769668  1.36697343 -1.00590084]
  [-1.30754494 -0.48441067 -1.39691296]]

 [[ 1.45605242  0.56929244  0.38995676]
  [-0.4478383  -0.87229282 -0.72166974]
  [ 0.28531631  0.34927861 -0.13407267]]

 [[-0.58256289  0.02386471  1.17071079]
  [ 0.90592298  0.19643843  1.29519651]
  [ 0.10240098 -2.15838624  0.36357735]]]


Create a vector comprising 7 equally spaced values, between 2 and 3

In [44]:
import random
x=np.linspace(2,3,7)
x


array([2.        , 2.16666667, 2.33333333, 2.5       , 2.66666667,
       2.83333333, 3.        ])

In [45]:
x.shape

(7,)

Use the choice function  to sample 5 values ​​from this last vector, once with replacement, and once without replacement

In [47]:
sample1 =np.random.choice(x, size=5, replace=True)
sample1

array([2.        , 3.        , 2.5       , 3.        , 2.66666667])

In [48]:
sample2 = np.random.choice(x, size=5, replace=False)
sample2



array([2.83333333, 2.66666667, 2.16666667, 2.5       , 2.33333333])

Create a vector corresponding to a sequence of numbers, from 13 to 19, counting in steps of one

In [26]:
my_vector = np.arange(13, 20, 1)
my_vector

array([13, 14, 15, 16, 17, 18, 19])

Create a 5*5 identity matrix

In [5]:
identity_matrix = np.eye(5)
identity_matrix

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

Create a 5*5 matrix of zeros, with 1 on the diagonal. 
Then specifically extract this diagonal

In [35]:
matrix = np.eye(5)
diagonal = np.diag(matrix)
diagonal

array([1., 1., 1., 1., 1.])

Complete this NumPy line to determine if the elements of a vector are finite (not infinite or not
a number)

In [29]:
a = np.array([1, 0, np.nan, np.inf]) 
print(np.isfinite(a))

[ True  True False False]


Complete this NumPy program to test element by element if it corresponds to infinity (positive
or negative)

In [6]:
x=np.array([1, 0, np.nan, np.inf])
print(np.isinf(x))

[False False False  True]


Complete this NumPy program to perform a comparison by element (equal, then equal to
a certain tolerance) of two given tables

In [7]:
x = np.array([72, 79, -135, 120, -10, 60, 100])
y = np.array([72, 79, -135, 120, -10, 60, 100.01])
print(np.equal(x, y))

[ True  True  True  True  True  True False]


**Subsetting & reshaping**

Create an array of 7 by 7 including only real numbers chosen from a normal distribution, then select only the first row, the first column, all columns up to the third, and the element of the second column and third row

In [54]:
array10 = np.random.normal(size=(7, 7))
array10


array([[-0.70261906, -0.23459388, -0.33345652, -0.14367654,  0.06618517,
         1.38199265, -0.17366913],
       [-1.21444357, -1.10162366, -0.09306072,  0.04244294,  2.00155233,
        -0.59762866,  0.38103543],
       [-1.18329383,  0.22922821,  0.31091505,  0.5485982 ,  0.73436872,
        -1.82022194,  1.2553458 ],
       [-1.11881875, -0.81133993, -0.34507981,  0.1209516 ,  1.91957401,
        -0.27799812,  1.21912006],
       [ 0.36338179,  0.19020285,  1.2614224 , -0.18759254,  1.7730821 ,
         0.0908294 , -0.24807269],
       [ 0.18012737, -0.63323532,  0.65599726,  0.62583097,  1.47250394,
         0.27521326,  0.18322928],
       [-0.06123912,  0.36821332, -0.27169816,  0.57594927, -0.05991418,
        -0.60272782, -0.77281995]])

In [ ]:
first_row = array10[0, :]
first_row1 = array10[0]
first_row
first_row1
first_column = array10[:, 0]
all_columns_up_to_third = array10[:, :3]
element_second_column_third_row = array10[2, 1]

In [55]:
first_row = array10[0, :]
first_row

array([-0.70261906, -0.23459388, -0.33345652, -0.14367654,  0.06618517,
        1.38199265, -0.17366913])

In [56]:
first_row1 = array10[0]
first_row1

array([-0.70261906, -0.23459388, -0.33345652, -0.14367654,  0.06618517,
        1.38199265, -0.17366913])

Create an array that is the repetition of one 1, two 2s, and three 3s, then from this vector, create a new array including the "unique" values ​​(i.e., 1, 2, and 3)

In [60]:
x=np.array([1,1,1,1,1,1,2,2,2,2,3,3,3])
print(np.unique(x))

[1 2 3]


Créez un array de 5*5 comprenant des chiffres entiers choisis aléatoirement, puis réalisez une transposition de cette matrice

In [8]:
x=np.random.normal(size=(5,5))
x


array([[-1.25962392, -0.83539519, -0.31257347,  1.23624552,  1.76676116],
       [-0.91970656, -0.00463144,  0.8319841 , -1.29814702,  0.54091851],
       [-0.11757629,  1.42680154, -2.14358903, -0.24176726,  1.0959716 ],
       [ 2.21460429,  1.14170914,  0.24743736, -0.71667153,  1.27903477],
       [ 1.14858381, -1.55154974,  2.2810598 ,  0.21410247,  0.91080075]])

In [9]:
print(np.transpose(x))

[[-1.25962392 -0.91970656 -0.11757629  2.21460429  1.14858381]
 [-0.83539519 -0.00463144  1.42680154  1.14170914 -1.55154974]
 [-0.31257347  0.8319841  -2.14358903  0.24743736  2.2810598 ]
 [ 1.23624552 -1.29814702 -0.24176726 -0.71667153  0.21410247]
 [ 1.76676116  0.54091851  1.0959716   1.27903477  0.91080075]]


Create a vector of 25 successive integers, then use reshape to make it a 5*5 matrix. Then play with the reshape function to illustrate how it works

In [5]:

vector1=np.arange(25)
reshaped_matrix = vector1.reshape((5, 5))
reshaped_matrix


array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

Make a broadcast of two arrays of your design

In [13]:
array1 = np.array([[1], [2], [3]]) 
array2 = np.array([4, 5, 6]).reshape((3,1))
array1+array2

array([[5],
       [7],
       [9]])

Illustrate “type casting” by changing the data type contained in an array of your choice

In [14]:
array10= np.array([1, 2, 3, 4, 5])
array10.dtype

dtype('int32')

In [16]:
array10.astype(np.float32)


array([1., 2., 3., 4., 5.], dtype=float32)

In [19]:
print(np.array([1,2,2,5,"ecem",True],dtype=str))


['1' '2' '2' '5' 'ecem' 'True']


In [20]:
print(np.array([1,2,0.2,5,True],dtype=np.int64).astype(np.float64))

[1. 2. 0. 5. 1.]


Create a 4*4 array including integers, which you will cut in half using vsplit

In [21]:
array12 = np.array([[1, 2, 3, 4],
                           [5, 6, 7, 8],
                           [9, 10, 11, 12],
                           [13, 14, 15, 16]])
print(np.vsplit(array12, 2))

[array([[1, 2, 3, 4],
       [5, 6, 7, 8]]), array([[ 9, 10, 11, 12],
       [13, 14, 15, 16]])]


Create a 4*4 array of integers, which you "unfold" into a 1D vector using the reshape command. You will then use the shuffle and permutation commands to mix these numbers

In [25]:
vector13 = np.array([[1, 2, 3, 4],
                           [5, 6, 7, 8],
                           [9, 10, 11, 12],
                           [13, 14, 15, 16]])
x=vector13.reshape(-1)
x

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16])

In [26]:
print(np.random.shuffle(x))

None


In [24]:
print(np.random.permutation(x))

[[13 14 15 16]
 [ 1  2  3  4]
 [ 9 10 11 12]
 [ 5  6  7  8]]


Merge a 3*3 matrix made of integers, with a vector of three elements, once horizontally, and once vertically

In [29]:
c1=np.array([[1, 2, 3],
            [4, 5, 6],
           [7, 8, 9]])
c2=np.array([10, 11, 12])
c3=c2.reshape((3,1))
c4=c2.reshape((1,3))
print(np.concatenate((c1,c4),axis=0))


[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


In [28]:
print(np.concatenate((c1,c3),axis=1))

[[ 1  2  3 10]
 [ 4  5  6 11]
 [ 7  8  9 12]]


Demonstrate your mastery and understanding of the resize command, then the argsort command. Make comments

In [34]:
ar5 = np.array([1, 2, 3, 4, 5])
x20=np.resize(ar5,(2,3)) # i passed  Array to be resized as the first argument and Shape of resized array as the second argument within the tuple
x20 # Resize the array to a new shape  reshape to a 2x3 matrix


array([[1, 2, 3],
       [4, 5, 1]])

In [35]:
print(np.argsort(ar5))
# Get the indices that would sort the array
# Print the  array

[0 1 2 3 4]


Write a NumPy program to get the n largest values ​​of an array, use np.partition and play with both positive and negative values ​​of n, the second argument of the function, before explaining in your words what is happening. pass

In [57]:
arr25= np.array([2, 0, 1, 5, 4, 9, 78, 34])  # Create an array
p = np.partition(arr25, 3) #all the elements less than the element at 5th position which is 5 are placed to the left side of 5 and all the elements greater than 5 are placed to the right of the separator element 
p



array([ 1,  0,  2,  4,  5,  9, 78, 34])

In [59]:
print(np.partition(arr25, (1, 3))) #The elements less than the element at index 1  are placed to the left, the elements between the elements at indices 1 and 3 are in some order in the middle, and the elements greater than or equal to the element at index 3 are placed to the right.

[ 0  1  2  4  5  9 78 34]


Sort a 2*2 array, on the one hand before having flattened it, and on the other hand after having flattened it

In [43]:
ar21 = np.array([[2, 1],
                [1, 10]])
print(np.sort(ar21, axis=0))  # sorted by x axis
print(ar21.flatten())
y=ar21.flatten()
y


[[ 1  1]
 [ 2 10]]
[ 2  1  1 10]


array([ 2,  1,  1, 10])

In [45]:
print(np.sort(y, axis=0)) # sorted by y axis after having flattened it

[ 1  1  2 10]


Produce a 1D array of the size of your choice, containing a random number of 2 between 5 and 10. Count the number of times the value 2 is repeated in the array.

In [13]:
arr30 = np.random.randint(2, 11,size=10)
arr30

array([ 8,  5,  9,  9,  6, 10,  5,  3,  7,  6])

In [12]:
c63 = np.count_nonzero(arr30 == 2)
c63

1

Create an integer vector of size 30 with numbers between 1 and 12. Then use np.isin to check if the numbers 4, 6 and 7 appeared in the sequence

In [73]:
x50=np.random.randint(1,13,size=30)
print(np.isin([4,6,7],x50))

[ True False  True]


**np.where**

Create an integer vector of size 30 with numbers between 1 and 12, then use the np.where function to identify indexes of numbers greater than 6

In [76]:
x60=np.random.randint(1,13,size=30)
print(np.where(x60>6))


(array([ 1,  2,  5,  6,  7, 10, 11, 21, 22, 23, 25, 27, 29], dtype=int64),)


**Données manquantes**

Create an array of 3 * 3 and introduce a missing value at index [0,0], via np.nan

In [78]:
c99 = np.random.random((3, 3))
c99

array([[0.49031848, 0.7679152 , 0.59865536],
       [0.82756082, 0.91446682, 0.65425933],
       [0.54489694, 0.78229812, 0.46177637]])

In [79]:
c99[0, 0] = np.nan
c99

array([[       nan, 0.7679152 , 0.59865536],
       [0.82756082, 0.91446682, 0.65425933],
       [0.54489694, 0.78229812, 0.46177637]])

Transform this missing value into zero using np.fillna

In [80]:
print(np.nan_to_num(c99))

[[0.         0.7679152  0.59865536]
 [0.82756082 0.91446682 0.65425933]
 [0.54489694 0.78229812 0.46177637]]


You have two sets of integers: A = {1, 2, 3, 4, 5} and B = {3, 4, 5, 6, 7}. Write a program in Python using the appropriate function to find the union of these two sets and return the result.

In [15]:
A= {1, 2, 3, 4, 5}
B = {3, 4, 5, 6, 7}
result95=A.union(B)
print(result95)

{1, 2, 3, 4, 5, 6, 7}


You have two sets of integers: A = {1, 2, 3, 4, 5} and B = {3, 4, 5, 6, 7}. Write a program in Python using the appropriate function to find the intersection of these two sets and return the result

In [1]:
A = {1, 2, 3, 4, 5}
B = {3, 4, 5, 6, 7}
result = A.intersection(B)
print("Intersection of sets A and B:", result)

Intersection of sets A and B: {3, 4, 5}


You have a set of integer values ​​= {2, 4, 6}, and a NumPy array = [1, 2, 3, 4, 5]. Write a program in Python using np.in1d ​​to check if each element in array belongs to the set values. The program must return an array of booleans indicating the membership of each element

In [14]:
v1={2,4,6}
ar1=np.array([1,2,3,4,5])
c45=np.in1d(ar1,list(v1))
print(c45)



[False  True False  True False]


You have two sets of integers: A = {1, 2, 3, 4, 5} and B = {3, 4, 5, 6, 7}. Write a program in Python using np.setdiff1d to find elements that are in A but not in B, then return the result.

In [6]:
import numpy as np
A = [1, 2, 3, 4, 5]
B = [3, 4, 5, 6, 7]
array125=np.array(A)
array126=np.array(B)
result = np.setdiff1d(array125, array126)
print(result)


[1 2]


Write a function that takes a NumPy array as input and returns a new array containing the differences between consecutive elements of the input array. For example, if the input is [1, 3, 7, 11], the result should be [2, 4, 4].

In [8]:
def return_new_array (array58):
    result21=np.diff(array58)
    return result21

In [9]:
input21=np.array([1,2,3,4,5,6])
return_new_array(input21)


array([1, 1, 1, 1, 1])

**Calculus with NumPy**

Create a matrix of 4*4 real numbers, both negative and positive, then calculate for each row the sum, average, and cumulative sum

In [84]:
x37=np.array([[1,2,-3,4],
            [1,2,3,-4],
            [-1,2,3,4],
            [1,-2,3,4]])
x37

array([[ 1,  2, -3,  4],
       [ 1,  2,  3, -4],
       [-1,  2,  3,  4],
       [ 1, -2,  3,  4]])

In [86]:
print(np.sum(x37, axis=1))
print(np.mean(x37, axis=1))
print(np.cumsum(x37, axis=1))


[4 2 8 6]
[1.  0.5 2.  1.5]
[[ 1  3  0  4]
 [ 1  3  6  2]
 [-1  1  4  8]
 [ 1 -1  2  6]]


Repeat the previous operation by averaging the absolute values ​​of the numbers, then the minimum value and the maximum value; you will finally create a last column using the maximum value with the np.round function

In [89]:
print(np.mean(np.abs(x37), axis=1))
print(np.min(x37, axis=1))
print(np.max(x37, axis=1))
print(np.round(np.max(x37, axis=1)))

[2.5 2.5 2.5 2.5]
[-3 -4 -1 -2]
[4 3 4 4]
[4 3 4 4]


Place 10 points randomly on a plane, then calculate the distance vectors between these different points. How many distance calculations do you do? Visualize points with matplotlib

Now visualize these distances on the plan, still with matplotlib

Create a list of randomly generated integers, and use np.mod (for modulo) to identify indexes of even numbers

**Fonctions universelles**

Take the vector {3,4,6,9} and use the add and multiply functions

In [90]:
v42= np.array([3, 4, 6, 9])
print(np.add(v42, -2))
print(np.multiply(v42, -1))


[1 2 4 7]
[-3 -4 -6 -9]


Use multiply.outer on two vectors, and explain the nature of the corresponding operations

In [91]:
v52 = np.array([1, 2, 3])
v53 = np.array([4, 5, 6])
print(np.multiply.outer(v52, v53))
#1*4 1*5 1*6
#2*4 2*5 2*6
#3*4 3*5 3*6 
# The resulting matrix has dimensions 3*3

[[ 4  5  6]
 [ 8 10 12]
 [12 15 18]]


Apply the negative function to the array [2,3,5]

In [92]:
arr85 = np.array([-1, -2, -3])
print(np.negative(arr85))


[1 2 3]


**Numpy and strings**

Merge two arrays each comprising two strings, using the np.char.add function

In [94]:
arr63 = np.array(['ecem', 'guven'])
arr64 = np.array([', ', 'hi'])
print(np.char.add(arr63, arr64))


['ecem, ' 'guvenhi']


array(['ecem', 'guven'], dtype='<U5')

Use the np.char.join function to insert the symbol ";" into a 5-character string. between each letter

In [95]:
arr95 = np.array(['ECEMX'])
print(np.char.join(',', arr95))

['E,C,E,M,X']


Use the np.char.upper function on the character string of your choice

In [96]:
arr96 = np.array(['ecem'])
print(np.char.upper(arr96))

['ECEM']


Use np.char.replace to demonstrate how to replace one string (in a sentence) with another

In [97]:
arr97 = np.array(['ecem'])
print(np.char.replace(arr97, 'e', 'i'))

['icim']


Use np.char.split to split an array containing two sentences into as many elements as there are words in them

In [98]:
arr98 = np.array(['ecem',"guven","ayse","gefe"])
print( np.char.split(arr98))

[list(['ecem']) list(['guven']) list(['ayse']) list(['gefe'])]


Create an array containing three strings including a repeated pattern, common to the three elements. Use np.char.count to count the number of times this pattern is repeated

In [99]:
arr99 = np.array(['ecmecmecmecmecmecmecmmcemcemcemce'])
print(np.char.count(arr99,"ecm" ))

[7]


Modify an array of length 5 by inserting elements, then removing some

In [102]:
arr48 = np.array([1, 2, 3, 4, 5])
print(np.delete(arr48,2))
print(np.insert(arr48,1,np.array([10, 20])))

[1 2 4 5]
[ 1 10 20  2  3  4  5]


Write a NumPy program to add a border (padded with 0s) around an existing array. You need two layers of zeros all around

In [105]:
x58=np.random.randint(2,10,size=(3,3))
x58

array([[2, 8, 4],
       [7, 4, 7],
       [8, 6, 3]])

In [106]:
print(np.pad(x58, pad_width=2, mode='constant', constant_values=0))

[[0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0]
 [0 0 2 8 4 0 0]
 [0 0 7 4 7 0 0]
 [0 0 8 6 3 0 0]
 [0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0]]


Write a NumPy program to create a 5x5 array with random values ​​and normalize it by row

In [107]:
x51=np.random.random((5,5))
x51

array([[0.00673   , 0.69891177, 0.31618941, 0.14913454, 0.09608347],
       [0.29722556, 0.94528375, 0.37225799, 0.40697574, 0.8860671 ],
       [0.43018891, 0.8175924 , 0.07587659, 0.3777699 , 0.86679357],
       [0.83594239, 0.13475924, 0.89582989, 0.69757992, 0.3234479 ],
       [0.76333109, 0.77754736, 0.4717447 , 0.39126636, 0.4365455 ]])

In [111]:
print((x51 - x51.mean(axis=1, keepdims=True)) / x51.std(axis=1, keepdims=True))

[[-1.00893598  1.82213079  0.25677237 -0.4264925  -0.64347468]
 [-1.03118972  1.3190925  -0.75907315 -0.6331639   1.10433427]
 [-0.28321179  1.03146982 -1.48559612 -0.46109945  1.19843755]
 [ 0.86810907 -1.48727624  1.06928067  0.40332761 -0.85344111]
 [ 1.16745536  1.2524611  -0.57607551 -1.05729302 -0.78654793]]


**Pour aller plus loin que la simple maîtrise des fonctions Numpy** (ChatGPT interdit)

Nous vous proposons quelques exercices de programmation, pour aller au-delà de la simple connaissance de fonctions

*Exercice 1*

Si le produit de deux nombres entiers est égal ou inférieur à 1 000, renvoyez le produit ; sinon, renvoyez leur somme. Nous attendons de vous que vous construisiez une fonction. numéro1 = 20,
nombre2 = 30, la sortie est 600

In [112]:
number1 = 20
number2 = 30
def product (number1,number2):
     product = number1 * number2
     if product <= 1000:
        return product
     else :
        return number1 + number2


In [113]:
x=product(50,60)
x

110

*Exercice 2*

Créez un programme qui invite l'utilisateur à saisir une chaîne, puis affiche
les caractères situés à des positions d'index paires. Par exemple, si la chaîne est
"exemple", le programme doit afficher les caractères "x", "m", "l".

In [154]:
name=input('enter your name')
def even_numbers(name):
    for char in name :
        if ord(char) % 2 == 0 :
         print(char)
even_numbers(name)




v
n


*Exercice 3*

Créez un programme qui prend une chaîne en entrée et supprime les caractères de
le début de la chaîne jusqu'à un index spécifié, ce qui donne une nouvelle chaîne.
Par exemple, si nous appelons la fonction remove chars(”example”, 3), la sortie
devrait être « mple ». Notez que l'index spécifié, noté 'n', doit être inférieur à la longueur de
la chaîne.

In [172]:
def remove_chars(stringname, index):
    if index < len(stringname):
        result_str = stringname[index:]
        return result_str

In [173]:
stringname = "example"
index= 3
remove_chars(stringname, index)

'mple'

*Exercice 4*

Itérer la liste de nombres donnée et imprimer uniquement les nombres divisibles
par 5:  la liste donnée est [10, 20, 33, 46, 55] Divisible par 5 : 10, 20, 55

In [142]:
list1=[10, 20, 33, 46, 55] 
for i in list1:
    if i %5 == 0 :
     print("Divisible by 5:",i)




Divisible by 5: 10
Divisible by 5: 20
Divisible by 5: 55


*Exercice 5*

Développer un programme qui détermine le nombre d'occurrences de la sous-chaîne
"Emma" dans une chaîne donnée.
• Donné : « Emma est une bonne développeuse. Emma est institutrice. »
• Résultat attendu : Emma est apparue 2 fois
Faites-le une fois avec la méthode « count » de chaîne, une fois sans.

In [177]:
counter=0
index=0
given = "Emma is a good developer. Emma is a teacher."
name="Emma"
while(index<len(given)):
    if given[index:index + len(name)]==name :
         counter+=1
         index+=len(name)
         
print("Emma appeared 2 times",counter) 



In [160]:
given1 = "Emma is a good developer. Emma is a teacher."
print(given1.count("Emma"))


2


*Exercice 6*

Écrivez un programme pour vérifier si le nombre donné est un nombre palindrome.
Un nombre palindrome est un nombre qui est le même après l'inverse. Par exemple
545, ce sont les nombres palindromes
Production attendue:
• numéro original 121 : Oui. le nombre donné est le numéro du palindrome
• numéro d'origine 125 : le numéro donné n'est pas un numéro palindrome

In [144]:
def palindrome(number) :
    number_str=str(number)
    if number_str == number_str[::-1]:
        print("Yes. the given number is the palindrome number")
    else:
        print("the given number is not a palindrome number")

In [145]:
num1 = 121
palindrome(num1)


Yes. the given number is the palindrome number


*Exercice 7*

Écrivez une boucle while pour afficher chaque caractère d'une chaîne et, si un caractère est
numéro : arrêter la boucle.

In [149]:
username=input("enter your name")
i=0
while(i<len(username)):
    print(username[i])
    i+=1



e
c
e
m
